# accounts/urls.py
from django.urls import path
from .views import (
    RegisterView, LoginView, DebugLoginView, FinanceView,
    WalletCreateView, TransactionView, TransactionDetailView,
    LogoutView, user_profile,
    BudgetCreateView, DebtCreateView, DebtDetailView, WalletDetailView, BudgetDetailView, BudgetHistoryView,
    CategoryCreateView, CategoryDetailView,
    LimitSubscriptionChallengeView, LimitSubscriptionActivateView, LimitSubscriptionCancelView,
    VerifyEmailCodeView, ResendVerificationCodeView,
    ForgotPasswordRequestView, ForgotPasswordConfirmView,
    SupportTicketView, SupportTicketDetailView, SupportChatMessageView,
    AdminSupportTicketView, AdminSupportTicketDetailView, AdminSupportChatView,
    AdminUserActivityView, AdminSupportTicketExportView, AdminUsersView, AdminUserDetailView,
)
from .tracker_views import (
    HabitListCreateView, HabitDetailView, HabitCompleteView,
    TaskListCreateView, TaskDetailView,
    TrackerListCreateView, TrackerDetailView, TrackerDashboardView,
    AIChatView, AIRecommendationView,
)
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    path('register/', csrf_exempt(RegisterView.as_view()), name='register'),
    path('verify-email/', csrf_exempt(VerifyEmailCodeView.as_view()), name='verify_email'),
    path('resend-verification/', csrf_exempt(ResendVerificationCodeView.as_view()), name='resend_verification'),
    path('login/', csrf_exempt(LoginView.as_view()), name='login'),
    path('debug-login/', csrf_exempt(DebugLoginView.as_view()), name='debug_login'),
    path('forgot-password/request/', csrf_exempt(ForgotPasswordRequestView.as_view()), name='forgot_password_request'),
    path('forgot-password/confirm/', csrf_exempt(ForgotPasswordConfirmView.as_view()), name='forgot_password_confirm'),
    path('finance/', FinanceView.as_view(), name='finance'),
    path('wallet/', WalletCreateView.as_view(), name='wallet_create'),
    path('wallet/<int:pk>/', WalletDetailView.as_view(), name='wallet_detail'),
    path('transaction/', TransactionView.as_view(), name='transaction'),
    path('transaction/<int:pk>/', TransactionDetailView.as_view(), name='transaction_detail'),
    path('budget/', BudgetCreateView.as_view(), name='budget_create'),
    path('budget/<int:pk>/', BudgetDetailView.as_view(), name='budget_detail'),
    path('budget/history/', BudgetHistoryView.as_view(), name='budget_history'),
    path('limit-subscription/challenge/', LimitSubscriptionChallengeView.as_view(), name='limit_subscription_challenge'),
    path('limit-subscription/activate/', LimitSubscriptionActivateView.as_view(), name='limit_subscription_activate'),
    path('limit-subscription/cancel/', LimitSubscriptionCancelView.as_view(), name='limit_subscription_cancel'),
    path('category/', CategoryCreateView.as_view(), name='category_create'),
    path('category/<int:pk>/', CategoryDetailView.as_view(), name='category_detail'),
    path('debt/', DebtCreateView.as_view(), name='debt_create'),
    path('debt/<int:pk>/', DebtDetailView.as_view(), name='debt_detail'),
    path('habits/', HabitListCreateView.as_view(), name='habit_list_create'),
    path('habits/<uuid:pk>/', HabitDetailView.as_view(), name='habit_detail'),
    path('habits/<uuid:pk>/complete/', HabitCompleteView.as_view(), name='habit_complete'),
    path('tasks/', TaskListCreateView.as_view(), name='task_list_create'),
    path('tasks/<uuid:pk>/', TaskDetailView.as_view(), name='task_detail'),
    path('trackers/', TrackerListCreateView.as_view(), name='tracker_list_create'),
    path('trackers/<uuid:pk>/', TrackerDetailView.as_view(), name='tracker_detail'),
    path('trackers/dashboard/', TrackerDashboardView.as_view(), name='tracker_dashboard'),
    path('ai/recommendations/', AIRecommendationView.as_view(), name='ai_recommendations'),
    path('ai/chat/', AIChatView.as_view(), name='ai_chat'),
    path('support/', SupportTicketView.as_view(), name='support_ticket'),
    path('support/<int:pk>/', SupportTicketDetailView.as_view(), name='support_ticket_detail'),
    path('support/chat/', SupportChatMessageView.as_view(), name='support_chat'),
    path('admin/support/tickets/', AdminSupportTicketView.as_view(), name='admin_support_tickets'),
    path('admin/support/tickets/export/', AdminSupportTicketExportView.as_view(), name='admin_support_tickets_export'),
    path('admin/support/tickets/<int:pk>/', AdminSupportTicketDetailView.as_view(), name='admin_support_ticket_detail'),
    path('admin/support/chat/<int:user_id>/', AdminSupportChatView.as_view(), name='admin_support_chat'),
    path('admin/user-activity/', AdminUserActivityView.as_view(), name='admin_user_activity'),
    path('admin/users/', AdminUsersView.as_view(), name='admin_users'),
    path('admin/users/<int:user_id>/', AdminUserDetailView.as_view(), name='admin_user_detail'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('user/', user_profile),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]
