# Generated by Codex on 2026-04-01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_userloginactivity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                ("frequency", models.CharField(choices=[("daily", "Daily"), ("weekly", "Weekly")], default="daily", max_length=10)),
                ("streak_count", models.PositiveIntegerField(default=0)),
                ("last_completed_date", models.DateField(blank=True, null=True)),
                ("points", models.PositiveIntegerField(default=0)),
                ("badge", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="habits", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["name", "created_at"],
                "indexes": [
                    models.Index(fields=["user", "frequency"], name="accounts_ha_user_id_198fbf_idx"),
                    models.Index(fields=["last_completed_date"], name="accounts_ha_last_co_2e8d49_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                ("category", models.CharField(choices=[("finance", "Finance"), ("personal", "Personal"), ("work", "Work")], default="finance", max_length=20)),
                ("due_date", models.DateTimeField()),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("priority", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")], default="medium", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["completed", "due_date", "-created_at"],
                "indexes": [
                    models.Index(fields=["user", "completed"], name="accounts_ta_user_id_f80ec7_idx"),
                    models.Index(fields=["due_date"], name="accounts_ta_due_dat_619918_idx"),
                    models.Index(fields=["priority"], name="accounts_ta_priorit_55f0d2_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Tracker",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                ("tracker_type", models.CharField(choices=[("daily", "Daily"), ("weekly", "Weekly"), ("custom", "Custom")], default="daily", max_length=10)),
                ("value", models.JSONField()),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("target_value", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("goal_direction", models.CharField(choices=[("at_least", "At least"), ("at_most", "At most")], default="at_least", max_length=10)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="trackers", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-date", "name"],
                "indexes": [
                    models.Index(fields=["user", "name"], name="accounts_tr_user_id_65409d_idx"),
                    models.Index(fields=["user", "date"], name="accounts_tr_user_id_54aa7d_idx"),
                ],
            },
        ),
    ]
