# Generated by Codex on 2026-04-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_habit_task_tracker"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAssistantMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("user", "User"), ("assistant", "Assistant")], default="assistant", max_length=10)),
                ("kind", models.CharField(choices=[("chat", "Chat"), ("proactive", "Proactive"), ("system", "System")], default="chat", max_length=12)),
                ("message", models.TextField()),
                ("source_key", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ai_messages", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["user", "created_at"], name="accounts_ai_user_id_44b2b8_idx"),
                    models.Index(fields=["user", "kind"], name="accounts_ai_user_id_738cb4_idx"),
                    models.Index(fields=["user", "source_key"], name="accounts_ai_user_id_71fb5f_idx"),
                ],
            },
        ),
    ]
