# Generated by Django 5.2.7 on 2026-04-01 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_aiassistantmessage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aiassistantmessage',
            new_name='accounts_ai_user_id_f516d8_idx',
            old_name='accounts_ai_user_id_44b2b8_idx',
        ),
        migrations.RenameIndex(
            model_name='aiassistantmessage',
            new_name='accounts_ai_user_id_4e39e5_idx',
            old_name='accounts_ai_user_id_738cb4_idx',
        ),
        migrations.RenameIndex(
            model_name='aiassistantmessage',
            new_name='accounts_ai_user_id_998344_idx',
            old_name='accounts_ai_user_id_71fb5f_idx',
        ),
        migrations.RenameIndex(
            model_name='habit',
            new_name='accounts_ha_user_id_c76266_idx',
            old_name='accounts_ha_user_id_198fbf_idx',
        ),
        migrations.RenameIndex(
            model_name='habit',
            new_name='accounts_ha_last_co_a33169_idx',
            old_name='accounts_ha_last_co_2e8d49_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='accounts_ta_user_id_85dd5f_idx',
            old_name='accounts_ta_user_id_f80ec7_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='accounts_ta_due_dat_84d807_idx',
            old_name='accounts_ta_due_dat_619918_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='accounts_ta_priorit_d67f14_idx',
            old_name='accounts_ta_priorit_55f0d2_idx',
        ),
        migrations.RenameIndex(
            model_name='tracker',
            new_name='accounts_tr_user_id_5e092f_idx',
            old_name='accounts_tr_user_id_65409d_idx',
        ),
        migrations.RenameIndex(
            model_name='tracker',
            new_name='accounts_tr_user_id_ae4668_idx',
            old_name='accounts_tr_user_id_54aa7d_idx',
        ),
    ]
